apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  MYSQL_URL: {{ .Values.app.env.mysqlUrl }}
  MYSQL_DATABASE: {{ .Values.mysql.database }}
