{{- if not .Values.mysql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: check-db-ready
        image: busybox:1.28
        command: ['sh', '-c', 'echo "Checking MySQL readiness"; until nc -z mysql-service 3306; do echo "Waiting for MySQL..."; sleep 2; done; echo "MySQL is ready";']
        timeoutSeconds: 300
      containers:
      - name: petclinic
        image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
        ports:
        - containerPort: {{ .Values.app.env.serverPort }}
        env:
        - name: SERVER_PORT
          value: "{{ .Values.app.env.serverPort }}"
        - name: MYSQL_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_URL
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_DATABASE
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        startupProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.app.env.serverPort }}
          initialDelaySeconds: 90
          periodSeconds: 10
          failureThreshold: 15
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.app.env.serverPort }}
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.app.env.serverPort }}
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
{{- end }}
