{{- if not .Values.mysql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup mysql-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mysql; sleep 2; done;']
      containers:
      - name: petclinic
        image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
        ports:
        - containerPort: {{ .Values.app.env.serverPort }}
        env:
        - name: SERVER_PORT
          value: "{{ .Values.app.env.serverPort }}"
        - name: MYSQL_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_URL
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_DATABASE
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: "com.mysql.cj.jdbc.Driver"
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: "org.hibernate.dialect.MySQL8Dialect"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.app.env.serverPort }}
          initialDelaySeconds: 120
          periodSeconds: 15
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.app.env.serverPort }}
          initialDelaySeconds: 120
          periodSeconds: 15
          timeoutSeconds: 10
{{- end }}
