apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
      - name: petclinic
        image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
        ports:
        - containerPort: {{ .Values.app.env.serverPort }}
        env:
        - name: SERVER_PORT
          value: "{{ .Values.app.env.serverPort }}"
        - name: MYSQL_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_URL
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_DATABASE
