apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  MYSQL_USER: {{ .Values.mysql.username | default "default_user" | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | default "default_password" | b64enc | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.database | default "default_database" | b64enc | quote }}
