{{- if not (hasKey .Release.Namespace "db-secrets") }}
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  MYSQL_USER: {{ .Values.mysql.user | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.database | b64enc | quote }}
{{- end }}
