{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
  - port: {{ .Values.mysql.service.port }}
  selector:
    app: {{ .Values.labels.db }}
{{- end }}
