{{- if not .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
  - port: {{ .Values.app.service.port }}
    targetPort: {{ .Values.app.env.serverPort }}
  selector:
    app: {{ .Values.labels.app }}
{{- end }}
