namespace: petclinic-dev

mysql:
  image: mysql:8.4
  username: petclinic
  password: petclinic
  rootPassword: root
  database: petclinic
  service:
    type: ClusterIP
    port: 3306
  storage:
    size: 8Gi

app:
  image:
    repository: 017820683847.dkr.ecr.us-east-1.amazonaws.com/petclinic-dev
    tag: latest
  replicas: 2
  service:
    type: LoadBalancer
    port: 8081
  env:
    serverPort: 8081
    mysqlUrl: jdbc:mysql://mysql-service:3306/petclinic

labels:
  app: petclinic
  db: mysql
